Repository BlackPythonDevs/blackpythondevs.github.io, pull requests merged in 2024-03, with the labels that each got.

#258 [translation] Sync `about.md` translation to Spanish
  _articles/es/about.md
Labels: translation

#261 [I18N] Update about.md in Spanish
  _articles/es/about.md
Labels: translation

#272 disable dark mode
  assets/css/bpd.css
  assets/css/pico.min.css
Labels: enhancement

#276 [A11Y] Fix some Website Accessibility Issues
  _layouts/index.html
  assets/css/bpd.css
  assets/css/pico.colors.min.css
Labels: enhancement, a11y

#278 [WCAG 2 AA] Update `pico` article.pico-background color
  assets/css/bpd.css
Labels: enhancement, design, css

#290 Update Gemfile.lock
  Gemfile.lock
Labels: enhancement

#291 [i18n] Translation Spanish index.html
  _articles/es/index.html
  _data/locales/es.yml
Labels: enhancement, i18n

#293 Add jekyll-sitemap plugin
  .gitignore
  Gemfile.lock
  _config.yml
Labels: enhancement
