Repository BlackPythonDevs/blackpythondevs.github.io, pull requests merged in 2024-09, with the labels that each got.

#427 fixed typo in leadership-summit-2024.md
  leadership-summit-2024.md
Labels: content, leadership summit

#452 Rename CONTRIBUTORS.md to MAINTAINERS.md and move Contributing Section of README into a new CONTRIBUTING.md
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
Labels: documentation, content

#483 Generate screenshot when "design_change" label is used
  .github/workflows/generate_screenshots.yml
  pytest.ini
  tests/test_design.py
Labels: design_change

#473 Optimize Pico CSS color profiles and update MAINTAINERS.md
  MAINTAINERS.md
  assets/css/pico.colors.min.css
Labels: design_change

#487 Modified the club page
  _data/books.json
  book-club.html
  tests/conftest.py
Labels: design_change
